### ISSUE TITLE
demo site no longer works

### ISSUE THREAD

**Issue by ziyadsaeed** [wch/shiny-jsdemo#6]
The demo site mentioned in readme.md http://glimmer.rstudio.com/winstontest/shiny-jsdemo/ no longer works. The app has been removed

**Comment by wch** [comment]
This example code is out of date. I'll update the README to reflect this.

Please see the example here:
http://shiny.rstudio.com/gallery/server-to-client-custom-messages.html
And the full source code (including the javascript file):
https://github.com/rstudio/shiny-examples/tree/master/061-server-to-client-custom-messages
